# This matrix builds VSYS with various JDKs and will be expanded to cover many more cases.   

name: VSYS Matrix
on: [push]


jobs:
  build:
   runs-on: ubuntu-latest
   strategy:
    matrix:
        java: [graalvm, zulu@1.08, zulu@1.11, openjdk@1.14, openjdk@1.13, openjdk@1.11, openjdk@1.8, openjdk@1.12]
  
  
   steps:
   - uses: actions/checkout@v2
     with:
       fetch-depth: 100
   - name: Fetch tags
     run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
   - uses: olafurpg/setup-scala@v5
     with:
       java-version: ${{ matrix.java }}
   - name: Build and Package
     run: sbt packageAll
        
           
        
